version: "3"

networks:
  repositories:
    external: false

volumes:
  gitea-data:

services:
  altinn_repositories:
    container_name: altinn-repositories
    image: gitea/gitea:1.5.1
    restart: always
    #networks:
    #  - altinncore_network
    volumes:
      - "gitea-data:/data"
    ports:
      - "3000:3000"
      - "222:22"
    build:
      context: .
      dockerfile: ./Dockerfile
#   depends_on:
#     - db
# db:
#   image: postgres:10.3
#   restart: always
#   environment:
#     - POSTGRES_USER=postgres
#     - POSTGRES_PASSWORD=gitea
#     - POSTGRES_DB=postgres
#   networks:
#     - repositories
#   volumes:
#      - gitea-data:/var/lib/postgresql/data
