name: Docker PDF Scan CI

on:
  push:
    branches: [ master ]
    paths:
      - 'src/Altinn.Platform/Altinn.Platform.Authentication/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/Altinn.Platform/Altinn.Platform.Authentication/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build src/Altinn.Platform/Altinn.Platform.PDF --file src/Altinn.Platform/Altinn.Platform.PDF/Dockerfile --tag altinn-pdf:${{github.sha}}
      
    - uses: Azure/container-scan@v0
      with:
        image-name: altinn-pdf:${{ github.sha }}
